name: Context
on: pull_request

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          echo ${{contains('hello', 'll')}}
          echo ${{startsWith('hello', 'he')}}
          echo ${{endsWith('hello', 'll')}}
          echo ${{format('Hello {0} {1}{2}','World','!','!')}}
  one:
    runs-on: ubuntu-latest
    # the maximum amount of minutes that this job will run before github cancels it
    # can be used in steps not only in jobs
    timeout-minutes: 360
    # conditional running job
    # after if dont need {{}} it's expression by default
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
     
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
         # all other steps will run even in failure
        continue-on-error: true
      - name: Dump job context
        # return true only if previos step fails
        if: failure()
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
      # will always run, returns true, even when canceled. 
        if: always()
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

