name: Using_Docker
on: push
jobs:
  node_docker:
    runs-on: ubuntu-latest
      # image from docker-hub
  services:
    app:
      image: alialaa17/node-api
      ports:
        - 3001:3000
    mongo:
      image: mongo
      ports:
        - "27017:27017"
    # we cab have env,ports, volumes, options
      image: node:alpine
    steps:
      - name: Post a User
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\",\"address\": \"dwded\"}'"
      - name: Get Users
        run: curl localhost:3001/api/users